/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao.onca;

import br.com.controle.Habitat;
import br.com.controle.Onca;
import br.com.entidade.ManterHabitatDAO;
import br.com.entidade.ManterOncaDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import java.sql.Timestamp;

/**
 *
 * @author gabi
 */
public class AlterarOnca extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlterarOnca.class.getName());
    Onca onca = new Onca();
    ManterOncaDAO oncaDAO = new ManterOncaDAO();

    /**
     * Creates new form AlterarOnca
     */
    public AlterarOnca() {
        initComponents();

        this.pesquisarHabitatsEMontarComboBox();
    }

    /**
     * Pesquisa todos os habitats cadastrados no banco para que seja
     * populado do combobox, assim evita de criar valores sem estarem cadastrados
     * no banco de dados.
     */
    private void pesquisarHabitatsEMontarComboBox() {
        ManterHabitatDAO habitatDAO = new ManterHabitatDAO();

        try {
            for (Habitat h : habitatDAO.pesquisarTudo()) {
                jCBhabitat.addItem(h);
            }
        } catch (Exception e) {
            throw new RuntimeException(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bTsexo = new javax.swing.ButtonGroup();
        bTstatus = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        jBpesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTcomportamento = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTdescricaoFisica = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jRviva = new javax.swing.JRadioButton();
        jRobito = new javax.swing.JRadioButton();
        jBlimpar = new javax.swing.JButton();
        jBeditar = new javax.swing.JButton();
        jTnome = new javax.swing.JTextField();
        jTidade = new javax.swing.JTextField();
        jTpeso = new javax.swing.JTextField();
        jRmacho = new javax.swing.JRadioButton();
        jRfemea = new javax.swing.JRadioButton();
        jCBhabitat = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Digite o ID de identificação da onca:");

        jBpesquisar.setText("Pesquisar");
        jBpesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do animal:");

        jLabel3.setText("Sexo:");

        jLabel4.setText("Idade:");

        jLabel5.setText("Peso:");

        jLabel6.setText("Comportamento:");

        jLabel7.setText("Descrição física:");

        jTcomportamento.setColumns(20);
        jTcomportamento.setRows(5);
        jTcomportamento.setText("\n");
        jScrollPane1.setViewportView(jTcomportamento);

        jTdescricaoFisica.setColumns(20);
        jTdescricaoFisica.setRows(5);
        jScrollPane2.setViewportView(jTdescricaoFisica);

        jLabel10.setText("Status de vida do animal:");

        bTstatus.add(jRviva);
        jRviva.setText("Viva");

        bTstatus.add(jRobito);
        jRobito.setText("Em óbito");

        jBlimpar.setText("Limpar");
        jBlimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBeditar.setText("Editar");
        jBeditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarActionPerformed(evt);
            }
        });

        bTsexo.add(jRmacho);
        jRmacho.setText("Macho");
        jRmacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRmachoActionPerformed(evt);
            }
        });

        bTsexo.add(jRfemea);
        jRfemea.setText("Fêmea");
        jRfemea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRfemeaActionPerformed(evt);
            }
        });

        jLabel9.setText("Habitat:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jBpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTidade, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRmacho)
                                        .addGap(50, 50, 50)
                                        .addComponent(jRfemea))
                                    .addComponent(jCBhabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(180, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRviva)
                        .addGap(42, 42, 42)
                        .addComponent(jRobito)
                        .addGap(0, 361, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jBlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jBeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRmacho)
                    .addComponent(jRfemea))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBhabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTidade, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTpeso, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRviva)
                            .addComponent(jRobito)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRmachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRmachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRmachoActionPerformed

    private void jRfemeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRfemeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRfemeaActionPerformed

    private void jBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarActionPerformed
        // TODO add your handling code here:
        onca.setIdOnca(Integer.parseInt(jTid.getText()));

        try {
            oncaDAO.pesquisarRegistro(onca);

            jTnome.setText(onca.getNome());
            jTidade.setText(Integer.toString(onca.getIdade()));
            jTpeso.setText(Double.toString(onca.getIdade()));
            jTcomportamento.setText(onca.getComportamento());
            jTdescricaoFisica.setText(onca.getDescricaoFisica());

            // setar sexo
            if (onca.getSexo().equals("F")) {
                jRfemea.setSelected(true);
            } else if (onca.getSexo().equals("M")) {
                jRmacho.setSelected(true);
            }

            // setar habitat
            Integer habitatOnca = onca.getIdHabitat();
            
            for (int i = 0; i < jCBhabitat.getItemCount(); i++) {
                Habitat h = jCBhabitat.getItemAt(i);

                if (h.getIdHabitat() == habitatOnca) {
                    jCBhabitat.setSelectedIndex(i); // deixa o habitat selecionado na combobox
                    break; // para o for, assim evita problemas, pois não faz sentido continuar percorrendo
                }
            }

            // setar viva ou morta
            if (onca.getInViva() == 1) {
                jRviva.setSelected(true);
            } else {
                jRobito.setSelected(true);
            }

            jBpesquisar.setEnabled(false);
            this.jTid.setEnabled(false);

        } catch (Exception e) {
            Logger.getLogger(AlterarOnca.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jBpesquisarActionPerformed

    private void jBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarActionPerformed
        // TODO add your handling code here:

        if (this.verificarCamposEmBranco()) {
            JOptionPane.showMessageDialog(null, "Verifique o(s) campo(s) não preenchido(s)!");
            return;
        }

        onca.setNome(jTnome.getText());
        onca.setSexo(this.pegarSexoOncaSelecionada());
        onca.setIdade(Integer.parseInt(jTidade.getText()));
        onca.setPeso(Double.parseDouble(jTpeso.getText()));
        onca.setComportamento(jTcomportamento.getText());
        onca.setDescricaoFisica(jTdescricaoFisica.getText());
        onca.setDataUltimaObservacao(new Timestamp(System.currentTimeMillis()));
        onca.setInViva(this.pegarStatusVidaOncaSelecionado());

        Habitat h = (Habitat) jCBhabitat.getSelectedItem();
        onca.setIdHabitat(h.getIdHabitat());

        try {
            oncaDAO.editarOnca(onca);

            this.jTnome.setText("");
            this.jRfemea.setSelected(false);
            this.jRmacho.setSelected(false);
            this.jTidade.setText("");
            this.jTpeso.setText("");
            this.jTcomportamento.setText("");
            this.jTdescricaoFisica.setText("");
            this.jRviva.setSelected(false);
            this.jRobito.setSelected(false);
            this.jCBhabitat.setSelectedIndex(-1);
            this.jBpesquisar.setEnabled(true);
            this.jTid.setText("");
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
        } catch (Exception e) {
            Logger.getLogger(AlterarOnca.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jBeditarActionPerformed

    private byte pegarStatusVidaOncaSelecionado() {
        if (jRviva.isSelected()) {
            return 1;
        } else {
            return 0;
        }
    }

    private String pegarSexoOncaSelecionada() {
        if (jRfemea.isSelected()) {
            return "F";
        } else {
            return "M";
        }
    }

    private boolean verificarCamposEmBranco() {
        boolean nenhumSexoSelecionado = !jRfemea.isSelected() && !jRmacho.isSelected();
        boolean nenhumStatusVidaSelecionado = !jRviva.isSelected() && !jRobito.isSelected();

        return jTnome.getText().isEmpty()
                || nenhumSexoSelecionado
                || nenhumStatusVidaSelecionado
                || jTidade.getText().isEmpty()
                || jTpeso.getText().isEmpty()
                || jTcomportamento.getText().isEmpty()
                || jTdescricaoFisica.getText().isEmpty()
                || jCBhabitat.getSelectedItem() == null;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AlterarOnca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bTsexo;
    private javax.swing.ButtonGroup bTstatus;
    private javax.swing.JButton jBeditar;
    private javax.swing.JButton jBlimpar;
    private javax.swing.JButton jBpesquisar;
    private javax.swing.JComboBox<Habitat> jCBhabitat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRfemea;
    private javax.swing.JRadioButton jRmacho;
    private javax.swing.JRadioButton jRobito;
    private javax.swing.JRadioButton jRviva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTcomportamento;
    private javax.swing.JTextArea jTdescricaoFisica;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTidade;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTpeso;
    // End of variables declaration//GEN-END:variables
}
