/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao.onca;

import br.com.visao.habitat.AlterarHabitat;
import br.com.visao.habitat.CadastroHabitat;
import br.com.visao.habitat.DeletarHabitat;
import br.com.visao.habitat.ListarHabitat;
import br.com.visao.pesquisador.AlterarPesquisador;
import br.com.visao.pesquisador.CadastrarPesquisador;
import br.com.visao.pesquisador.DeletarPesquisador;
import br.com.visao.pesquisador.ListarPesquisador;
import br.com.visao.relatorios.RelatorioMonitoramento;
import br.com.visao.relatorios.ListarelatorioObitos;

/**
 *
 * @author gabi
 */
public class MenuOnca extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuOnca.class.getName());

    /**
     * Creates new form MenuOnca
     */
    public MenuOnca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMcadastrar = new javax.swing.JMenu();
        jRcadastrarOnca = new javax.swing.JRadioButtonMenuItem();
        jRcadastrarPesquisador = new javax.swing.JRadioButtonMenuItem();
        jRcadastrarHabitat = new javax.swing.JRadioButtonMenuItem();
        jMexcluir = new javax.swing.JMenu();
        jRexcluirOnca = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRexcluirHabitat = new javax.swing.JRadioButtonMenuItem();
        jMeditar = new javax.swing.JMenu();
        jRAlterarOncas = new javax.swing.JRadioButtonMenuItem();
        jRalterarPesquisador = new javax.swing.JRadioButtonMenuItem();
        jRalterarHabitat = new javax.swing.JRadioButtonMenuItem();
        jMListar = new javax.swing.JMenu();
        jRlistarOncas = new javax.swing.JRadioButtonMenuItem();
        jRlistarPesquisador = new javax.swing.JRadioButtonMenuItem();
        jRListarHabitat = new javax.swing.JRadioButtonMenuItem();
        jMListar1 = new javax.swing.JMenu();
        jRMonitoramento = new javax.swing.JRadioButtonMenuItem();
        jROncasMortas = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMcadastrar.setText("Cadatrar");

        jRcadastrarOnca.setSelected(true);
        jRcadastrarOnca.setText("Cadastrar Onça");
        jRcadastrarOnca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRcadastrarOncaActionPerformed(evt);
            }
        });
        jMcadastrar.add(jRcadastrarOnca);

        jRcadastrarPesquisador.setSelected(true);
        jRcadastrarPesquisador.setText("Cadastrar Pesquisador");
        jRcadastrarPesquisador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRcadastrarPesquisadorActionPerformed(evt);
            }
        });
        jMcadastrar.add(jRcadastrarPesquisador);

        jRcadastrarHabitat.setSelected(true);
        jRcadastrarHabitat.setText("Cadastrar Habitat");
        jRcadastrarHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRcadastrarHabitatActionPerformed(evt);
            }
        });
        jMcadastrar.add(jRcadastrarHabitat);

        jMenuBar1.add(jMcadastrar);

        jMexcluir.setText("Excluir Cadastro");

        jRexcluirOnca.setSelected(true);
        jRexcluirOnca.setText("Excluir onça");
        jRexcluirOnca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRexcluirOncaActionPerformed(evt);
            }
        });
        jMexcluir.add(jRexcluirOnca);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Excluir Pesquisador");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMexcluir.add(jRadioButtonMenuItem1);

        jRexcluirHabitat.setSelected(true);
        jRexcluirHabitat.setText("Excluir Habitat");
        jRexcluirHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRexcluirHabitatActionPerformed(evt);
            }
        });
        jMexcluir.add(jRexcluirHabitat);

        jMenuBar1.add(jMexcluir);

        jMeditar.setText("Alterar Cadastro");

        jRAlterarOncas.setSelected(true);
        jRAlterarOncas.setText("Alterar Onça");
        jRAlterarOncas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRAlterarOncasActionPerformed(evt);
            }
        });
        jMeditar.add(jRAlterarOncas);

        jRalterarPesquisador.setSelected(true);
        jRalterarPesquisador.setText("Alterar Pesquisador");
        jRalterarPesquisador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRalterarPesquisadorActionPerformed(evt);
            }
        });
        jMeditar.add(jRalterarPesquisador);

        jRalterarHabitat.setSelected(true);
        jRalterarHabitat.setText("Alterar Habitat");
        jRalterarHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRalterarHabitatActionPerformed(evt);
            }
        });
        jMeditar.add(jRalterarHabitat);

        jMenuBar1.add(jMeditar);

        jMListar.setText("Listar Cadastros");

        jRlistarOncas.setSelected(true);
        jRlistarOncas.setText("Listar Onças");
        jRlistarOncas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRlistarOncasActionPerformed(evt);
            }
        });
        jMListar.add(jRlistarOncas);

        jRlistarPesquisador.setSelected(true);
        jRlistarPesquisador.setText("Listar Pesquisador");
        jRlistarPesquisador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRlistarPesquisadorActionPerformed(evt);
            }
        });
        jMListar.add(jRlistarPesquisador);

        jRListarHabitat.setSelected(true);
        jRListarHabitat.setText("Listar Habitat");
        jRListarHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRListarHabitatActionPerformed(evt);
            }
        });
        jMListar.add(jRListarHabitat);

        jMenuBar1.add(jMListar);

        jMListar1.setText("Relatórios");

        jRMonitoramento.setSelected(true);
        jRMonitoramento.setText("Histórico de monitoramento");
        jRMonitoramento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRMonitoramentoActionPerformed(evt);
            }
        });
        jMListar1.add(jRMonitoramento);

        jROncasMortas.setSelected(true);
        jROncasMortas.setText("Histórico de onças mortas");
        jROncasMortas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jROncasMortasActionPerformed(evt);
            }
        });
        jMListar1.add(jROncasMortas);

        jMenuBar1.add(jMListar1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRexcluirOncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRexcluirOncaActionPerformed
        // TODO add your handling code here:
        DeletarOnca deletarOnca = new DeletarOnca();
        deletarOnca.show();
    }//GEN-LAST:event_jRexcluirOncaActionPerformed

    private void jRlistarOncasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRlistarOncasActionPerformed
        // TODO add your handling code here:
        ListarOnca listarOnca = new ListarOnca();
        listarOnca.show();
    }//GEN-LAST:event_jRlistarOncasActionPerformed

    private void jRalterarPesquisadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRalterarPesquisadorActionPerformed
        // TODO add your handling code here:
        AlterarPesquisador alterarPesquisador = new AlterarPesquisador();
        alterarPesquisador.show();
    }//GEN-LAST:event_jRalterarPesquisadorActionPerformed

    private void jRexcluirHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRexcluirHabitatActionPerformed
        // TODO add your handling code here:
        DeletarHabitat deleteDeletarHabitat = new DeletarHabitat();
        deleteDeletarHabitat.show();
    }//GEN-LAST:event_jRexcluirHabitatActionPerformed

    private void jRcadastrarHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRcadastrarHabitatActionPerformed
        // TODO add your handling code here:
        CadastroHabitat cadastroHabitat = new CadastroHabitat();
        cadastroHabitat.show();
    }//GEN-LAST:event_jRcadastrarHabitatActionPerformed

    private void jRalterarHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRalterarHabitatActionPerformed
        // TODO add your handling code here:
        AlterarHabitat alterarHabitat = new AlterarHabitat();
        alterarHabitat.show();
    }//GEN-LAST:event_jRalterarHabitatActionPerformed

    private void jRListarHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRListarHabitatActionPerformed
        // TODO add your handling code here:
        ListarHabitat listarHabitat = new ListarHabitat();
        listarHabitat.show();
    }//GEN-LAST:event_jRListarHabitatActionPerformed

    private void jRlistarPesquisadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRlistarPesquisadorActionPerformed
        // TODO add your handling code here:
        ListarPesquisador listarPesquisador = new ListarPesquisador();
        listarPesquisador.show();
    }//GEN-LAST:event_jRlistarPesquisadorActionPerformed

    private void jRMonitoramentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRMonitoramentoActionPerformed
        // TODO add your handling code here:
        RelatorioMonitoramento monitoramento = new RelatorioMonitoramento();
        monitoramento.show();
    }//GEN-LAST:event_jRMonitoramentoActionPerformed

    private void jROncasMortasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jROncasMortasActionPerformed
        // TODO add your handling code here:
        ListarelatorioObitos relatorioObitos = new ListarelatorioObitos();
        relatorioObitos.show();
    }//GEN-LAST:event_jROncasMortasActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
        DeletarPesquisador deletarPesquisador = new DeletarPesquisador();
        deletarPesquisador.show();
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRcadastrarPesquisadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRcadastrarPesquisadorActionPerformed
        // TODO add your handling code here:
        CadastrarPesquisador cadastrarPesquisador = new CadastrarPesquisador();
        cadastrarPesquisador.show();
    }//GEN-LAST:event_jRcadastrarPesquisadorActionPerformed

    private void jRcadastrarOncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRcadastrarOncaActionPerformed
        // TODO add your handling code here:
        CadastroOnca cadastroOnca = new CadastroOnca();
        cadastroOnca.show();
    }//GEN-LAST:event_jRcadastrarOncaActionPerformed

    private void jRAlterarOncasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRAlterarOncasActionPerformed
        // TODO add your handling code here:
        AlterarOnca alterarOnca = new AlterarOnca();
        alterarOnca.show();
    }//GEN-LAST:event_jRAlterarOncasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuOnca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMListar;
    private javax.swing.JMenu jMListar1;
    private javax.swing.JMenu jMcadastrar;
    private javax.swing.JMenu jMeditar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMexcluir;
    private javax.swing.JRadioButtonMenuItem jRAlterarOncas;
    private javax.swing.JRadioButtonMenuItem jRListarHabitat;
    private javax.swing.JRadioButtonMenuItem jRMonitoramento;
    private javax.swing.JRadioButtonMenuItem jROncasMortas;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRalterarHabitat;
    private javax.swing.JRadioButtonMenuItem jRalterarPesquisador;
    private javax.swing.JRadioButtonMenuItem jRcadastrarHabitat;
    private javax.swing.JRadioButtonMenuItem jRcadastrarOnca;
    private javax.swing.JRadioButtonMenuItem jRcadastrarPesquisador;
    private javax.swing.JRadioButtonMenuItem jRexcluirHabitat;
    private javax.swing.JRadioButtonMenuItem jRexcluirOnca;
    private javax.swing.JRadioButtonMenuItem jRlistarOncas;
    private javax.swing.JRadioButtonMenuItem jRlistarPesquisador;
    // End of variables declaration//GEN-END:variables
}
