services:
  backend:
    build:
      context: ./doacao-sangue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      - frontend

  frontend:
    build:
      context: ./doacao-sangue-web
      dockerfile: Dockerfile
    ports:
      - "80:80"
