spring:
  application:
    name: doacao‑sangue

  h2:
    console:
      enabled: true
      path: /h2‑console

  datasource:
    url: jdbc:h2:mem:hemocentro
    driverClassName: org.h2.Driver
    username: ga
    password: "1234"
